service: dota2-assistant-backend
frameworkVersion: '3'

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_REGION, 'ap-northeast-1'}
  environment:
    NODE_OPTIONS: --enable-source-maps
    HERO_CACHE_TABLE: ${self:custom.heroCacheTable}
    HERO_CACHE_TTL_SECONDS: ${env:HERO_CACHE_TTL_SECONDS, ''}
    ALLOWED_ORIGINS: ${env:ALLOWED_ORIGINS, ''}
  httpApi:
    cors:
      allowedOrigins:
        - ${env:FRONTEND_ORIGIN, '*'}
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
      allowCredentials: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource:
            - !GetAtt HeroCacheTable.Arn

functions:
  api:
    handler: src/lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

resources:
  Resources:
    HeroCacheTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.heroCacheTable}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

custom:
  heroCacheTable: ${env:HERO_CACHE_TABLE, '${self:service}-${self:provider.stage}-hero-cache'}
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node18
    platform: node
    format: cjs
    external:
      - aws-sdk
    tsconfig: tsconfig.json
